export default [
  {
    schoolName: "清平实验学校（小学部）",
    schoolClass: 8,
    belongsText:
      "(1)107国道以西，中心路以东，新沙路以北的新桥街道范围；\n(2)中心路以西，宝安大道以东，蚝乡路以北的新桥街道范围；\n(3)宝安大道以西至海边，北环路以北的沙井街道范围。",
    schoolType: 1,
    schoolTel: "23211175,27782491",
    educationType: 1,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "范围（1）和（2）接受所有符合就读条件的适龄儿童；\n范围（3）接受深户学区内租房或有特殊住房，非深户学区内购房、租房或有特殊住房的符合就读条件的适龄儿童",
  },
  {
    schoolName: "新桥小学",
    schoolClass: 8,
    belongsText:
      "(1)107国道以西，中心路以东，新沙路以北的新桥街道范围；\n(2)中心路以西，宝安大道以东，蚝乡路以北的新桥街道范围；\n(3)宝安大道以西至海边，北环路以北的沙井街道范围。",
    schoolType: 1,
    schoolTel: "27256341,27256136",
    educationType: 1,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "清平实验学校东校区（小学部）（借址清平实验学校）",
    schoolClass: 2,
    belongsText:
      "(1)107国道以西，中心路以东，新沙路以北的新桥街道范围；\n(2)中心路以西，宝安大道以东，蚝乡路以北的新桥街道范围；\n(3)宝安大道以西至海边，北环路以北的沙井街道范围。",
    schoolType: 1,
    schoolTel: "23211175,27782491",
    educationType: 1,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "壆岗小学",
    schoolClass: 8,
    belongsText:
      "(1)壆岗社区、西荟城、新沙路以南的万科、拾悦城；\n(2)宝安大道以西，北环路以南，立岗北路→沙井中学东围墙→盛芳园西围墙→西荟城三期西围墙以东，新沙路以北；\n(3)宝安大道以西，西环路以东，新沙路以南，鞍山五路→沙中路以北围合的区域。",
    schoolType: 1,
    schoolTel: "23147953",
    educationType: 1,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "范围（1）接受宝安户籍学区内购房或有祖屋、深圳其它区户籍学区内购房的符合就读条件的适龄儿童；\n范围（2）和（3）接受深户学区内租房或有特殊住房，非深户学区内购房、租房或有特殊住房的符合就读条件的适龄儿童",
  },
  {
    schoolName: "宝安中学外国语学校（集团）拾悦小学",
    schoolClass: 3,
    belongsText:
      "(1)壆岗社区、西荟城、新沙路以南的万科、拾悦城；\n(2)宝安大道以西，北环路以南，立岗北路→沙井中学东围墙→盛芳园西围墙→西荟城三期西围墙以东，新沙路以北；\n(3)宝安大道以西，西环路以东，新沙路以南，鞍山五路→沙中路以北围合的区域。",
    schoolType: 1,
    schoolTel: "29995688",
    educationType: 1,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安中学外国语学校（集团）博雅学校（小学部）",
    schoolClass: 4,
    belongsText:
      "(1)壆岗社区、西荟城、新沙路以南的万科、拾悦城；\n(2)宝安大道以西，北环路以南，立岗北路→沙井中学东围墙→盛芳园西围墙→西荟城三期西围墙以东，新沙路以北；\n(3)宝安大道以西，西环路以东，新沙路以南，鞍山五路→沙中路以北围合的区域。",
    schoolType: 1,
    schoolTel: "29969339",
    educationType: 1,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "荣根学校(小学部)",
    schoolClass: 8,
    belongsText:
      "（1）沙一、沙二、沙三、沙四、民主、共和、步涌、后亭、衙边、辛养、东塘社区，沙中路→万乐路以北的沙头社区，新沙路以北的万科；\n\n（2）立岗北路→沙井中学东围墙→壆岗盛芳园西围墙→西荟城三期西围墙以西，沙井大街→北帝堂一路以东；北环路以南，新沙路以北围合的区域。",
    schoolType: 0,
    schoolTel: "29855443",
    educationType: 1,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "可分享【和一学校小学部、茭塘小学、会展城实验学校小学部】或【壆岗小学、拾悦小学、宝安中学外国语学校集团博雅学校小学部】学位）",
  },
  {
    schoolName: "宝安中学（集团）第二外国语学校（小学部）",
    schoolClass: 5,
    belongsText:
      "107国道以西，新沙路以南，中心路以东，凤塘大道以北的新桥街道范围。",
    schoolType: 1,
    schoolTel: "29873923",
    educationType: 1,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "可分享【深圳外国语学校宝安学校（小学部）与万丰小学】学位",
  },
  {
    schoolName: "上星学校（小学部）",
    schoolClass: 6,
    belongsText:
      "107国道以西，新沙路以南，中心路以东，凤塘大道以北的新桥街道范围。",
    schoolType: 1,
    schoolTel: "27888316,27888306",
    educationType: 1,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安小学（集团）蚝业小学",
    schoolClass: 5,
    belongsText:
      "(1)蚝乡社区（原蚝一、蚝二）、沙蚝社区（原蚝三、蚝四）；\n(2)沙井大街→北帝堂一路以西，西环路以东；北环路以南，新沙路以北。\n(3)沙井西环路以西至海边，沙井北环路以南，沙中路→万乐路以北；",
    schoolType: 0,
    schoolTel: "27202082",
    educationType: 1,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "可分享【和一学校小学部、茭塘小学、会展城实验学校小学部】学位）",
  },
  {
    schoolName: "深圳外国语学校宝安学校（集团）万丰小学",
    schoolClass: 7,
    belongsText: "宝安大道以东，蚝乡路以南，中心路以西，凤塘大道以北。",
    schoolType: 1,
    schoolTel: "29931037,27288763",
    educationType: 1,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "深圳外国语学校宝安学校（小学部）",
    schoolClass: 12,
    belongsText: "宝安大道以东，蚝乡路以南，中心路以西，凤塘大道以北。",
    schoolType: 1,
    schoolTel: "23088817",
    educationType: 1,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "黄埔小学",
    schoolClass: 8,
    belongsText: "107国道以东的新桥街道范围。",
    schoolType: 2,
    schoolTel: "27242987",
    educationType: 1,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安小学（集团）茭塘小学",
    schoolClass: 5,
    belongsText:
      "东至宝安大道，南至沙福河（沙井街道和福海街道的边界），西至沙井路，北以鞍山五路-沙中路为界的围合片区。",
    schoolType: 1,
    schoolTel: "27866300",
    educationType: 1,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "和一学校（小学部）",
    schoolClass: 4,
    belongsText:
      "(1)东至沙井路，南至沙福路，西至海边，北以沙中路-万乐路为界的围合片区。\n(2)北至沙福路，东至松福大道，南至福洲大道，西至海边的围合片区仅可报会展城实验学校(小学部）",
    schoolType: 1,
    schoolTel: "23010431",
    educationType: 1,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "会展城实验学校(小学部）",
    schoolClass: 4,
    belongsText:
      "(1)东至沙井路，南至沙福路，西至海边，北以沙中路-万乐路为界的围合片区。\n(2)北至沙福路，东至松福大道，南至福洲大道，西至海边的围合片区仅可报会展城实验学校(小学部）",
    schoolType: 1,
    schoolTel: "29873923",
    educationType: 1,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "沙井中学(初中部)",
    schoolClass: 12,
    belongsText: "宝安大道以西至海边，沙福路以北的沙井街道范围。",
    schoolType: 1,
    schoolTel: "27684386",
    educationType: 2,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "荣根学校（初中部）",
    schoolClass: 4,
    belongsText: "宝安大道以西至海边，沙福路以北的沙井街道范围。",
    schoolType: 1,
    schoolTel: "29855443",
    educationType: 2,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "和一学校（初中部）",
    schoolClass: 4,
    belongsText:
      "（1）东至宝安大道，南以沙福河→沙井路→沙福路为界，西至海边，北以鞍山五路→沙中路→万乐路为界的围合片区。\n（2）北至沙福路，东至松福大道，南至福洲大道，西至海边的围合片区仅可报会展城实验学校(初中部）",
    schoolType: 1,
    schoolTel: "23010431",
    educationType: 2,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "会展城实验学校(初中部）",
    schoolClass: 2,
    belongsText:
      "（1）东至宝安大道，南以沙福河→沙井路→沙福路为界，西至海边，北以鞍山五路→沙中路→万乐路为界的围合片区。\n（2）北至沙福路，东至松福大道，南至福洲大道，西至海边的围合片区仅可报会展城实验学校(初中部）",
    schoolType: 1,
    schoolTel: "29873923",
    educationType: 2,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安中学（集团）第二外国语学校(初中部)",
    schoolClass: 7,
    belongsText:
      "（1）107国道以东的新桥街道范围；\n（2）107国道以西，中心路以东，凤塘大道以北的新桥街道范围；\n（3）中心路以西，宝安大道以东，蚝乡路以北的新桥街道范围。",
    schoolType: 1,
    schoolTel: "29873923",
    educationType: 2,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "可分享深圳外国语学校宝安学校（初中部）学位",
  },
  {
    schoolName: "清平实验学校（初中部）",
    schoolClass: 7,
    belongsText:
      "（1）107国道以东的新桥街道范围；\n（2）107国道以西，中心路以东，凤塘大道以北的新桥街道范围；\n（3）中心路以西，宝安大道以东，蚝乡路以北的新桥街道范围。",
    schoolType: 1,
    schoolTel: "23211175,27782491",
    educationType: 2,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "上星学校（初中部）",
    schoolClass: 6,
    belongsText:
      "（1）107国道以东的新桥街道范围；\n（2）107国道以西，中心路以东，凤塘大道以北的新桥街道范围；\n（3）中心路以西，宝安大道以东，蚝乡路以北的新桥街道范围。",
    schoolType: 1,
    schoolTel: "27888316,27888306",
    educationType: 2,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "深圳外国语学校宝安学校（初中部）",
    schoolClass: 8,
    belongsText: "宝安大道以东，蚝乡路以南，中心路以西，凤塘大道以北。",
    schoolType: 2,
    schoolTel: "23222432",
    educationType: 2,
    schoolBelongTo: 3,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
];
