export default [
  {
    schoolName: "宝安区实验学校（集团）官田学校（小学部）",
    schoolClass: 10,
    belongsText:
      "(1)官田社区：黎光、官田、塘坑；\n(2)罗租社区：龙眼山、罗租；\n(3)水田社区：水田、三祝里；\n(4)石龙社区：石龙",
    schoolType: 1,
    schoolTel: "27760354转8516",
    educationType: 1,
    schoolBelongTo: 1,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安中学（集团）石岩外国语学校（小学部）",
    schoolClass: 10,
    belongsText: "",
    schoolType: "",
    schoolTel: "27760278",
    educationType: 1,
    schoolBelongTo: 1,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "湖光学校（小学部）",
    schoolClass: 4,
    belongsText: "",
    schoolType: "",
    schoolTel: "13310867596",
    educationType: 1,
    schoolBelongTo: 1,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "天骄小学（集团）湖东小学",
    schoolClass: 4,
    belongsText: "",
    schoolType: "",
    schoolTel: "27619978",
    educationType: 1,
    schoolBelongTo: 1,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "新安中学（集团）龙田学校（小学部）",
    schoolClass: 4,
    belongsText: "",
    schoolType: "",
    schoolTel: "23592976",
    educationType: 1,
    schoolBelongTo: 1,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安小学（集团）罗租小学",
    schoolClass: 6,
    belongsText:
      "(1)罗租社区：罗租、龙眼山；\n(2)上屋社区：上下屋、田心、园美；\n(3)龙腾社区：径贝、石岩、上排、下排；\n(4)浪心社区：砖厂",
    schoolType: 1,
    schoolTel: "27632161",
    educationType: 1,
    schoolBelongTo: 1,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "滨海小学（集团）上屋小学",
    schoolClass: 7,
    belongsText: "",
    schoolType: "",
    schoolTel: "27645322",
    educationType: 1,
    schoolBelongTo: 1,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "阳台山小学（借址石岩湖学校）",
    schoolClass: 6,
    belongsText: "",
    schoolType: "",
    schoolTel: "27082944",
    educationType: 1,
    schoolBelongTo: 1,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "智造城实验学校(小学部）(借址悦云花园配建幼儿园（暂定名）)",
    schoolClass: 4,
    belongsText: "",
    schoolType: "",
    schoolTel: "27648235",
    educationType: 1,
    schoolBelongTo: 1,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "石岩湖学校（小学部）",
    schoolClass: 8,
    belongsText:
      "(1)浪心社区：浪心、石新、砖厂；\n(2)龙腾社区：石岩；\n(3)塘头社区：塘头；\n(4)宝源社区：料坑、麻布；\n(5)应人石社区：应人石（含牛成）",
    schoolType: 1,
    schoolTel: "27648235",
    educationType: 1,
    schoolBelongTo: 1,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "范围(1)的砖厂片区只接受宝安户籍学区内购房或有祖屋的符合就读条件的适龄儿童",
  },
  {
    schoolName: "宝安中学（集团）塘头学校（小学部）",
    schoolClass: 8,
    belongsText: "",
    schoolType: "",
    schoolTel: "29989828",
    educationType: 1,
    schoolBelongTo: 1,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安中学（集团）石岩外国语学校（初中部）",
    schoolClass: 12,
    belongsText: "石岩街道",
    schoolType: 1,
    schoolTel: "27609727",
    educationType: 2,
    schoolBelongTo: 1,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安区实验学校（集团）官田学校（初中部）",
    schoolClass: 8,
    belongsText: "",
    schoolType: "",
    schoolTel: "27619585",
    educationType: 2,
    schoolBelongTo: 1,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "湖光学校（初中部）",
    schoolClass: 4,
    belongsText: "",
    schoolType: "",
    schoolTel: "13310867596",
    educationType: 2,
    schoolBelongTo: 1,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "新安中学（集团）龙田学校（初中部）",
    schoolClass: 4,
    belongsText: "",
    schoolType: "",
    schoolTel: "23592976",
    educationType: 2,
    schoolBelongTo: 1,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安中学（集团）塘头学校（初中部）",
    schoolClass: 8,
    belongsText: "石岩街道",
    schoolType: 1,
    schoolTel: "29989828",
    educationType: 2,
    schoolBelongTo: 1,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "石岩湖学校（初中部）",
    schoolClass: 8,
    belongsText: "",
    schoolType: "",
    schoolTel: "27648235",
    educationType: 2,
    schoolBelongTo: 1,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
];
