export default [
  {
    schoolName: "松岗第二小学",
    schoolClass: 11,
    belongsText:
      "北至沙江路，西至107国道，南至东方大道的松岗街道行政区域范围；主要社区有：楼岗，东方（部分），松岗社区麒麟新村、东风村，山门社区。主要小区有：宝利豪庭、联投东方华府（1、2期）、居乐苑、集信大厦、翡翠阳光名苑、汇智百盛花园、璟荟名庭。",
    schoolType: "分享学区（可分享【松岗第一小学和红星小学】学位）",
    schoolTel: "29626522",
    educationType: 1,
    schoolBelongTo: 4,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "松岗第一小学",
    schoolClass: 6,
    belongsText:
      "东至107国道，南至河滨南路，北至沙江路的松岗街道范围。主要社区有：松岗社区（部分），花果山社区，松涛社区（部分），红星社区格布村、温屋村、蚝涌村、松新村、西坊村、湾头村、南岸村，松岗社区坑尾村，洪桥头社区。主要小区有：红星花园、松河瑞园。\n(2)北至沙江路，西至107国道，南至东方大道的松岗街道范围。主要社区有：楼岗社区，东方社区（部分），松岗社区麒麟新村、东风村，山门社区。主要小区有：宝利豪庭、联投东方华府（1、2期）、居乐苑、集信大厦、翡翠阳光名苑、汇智百盛花园、璟荟名庭。",
    schoolType: 1,
    schoolTel: "29623471",
    educationType: 1,
    schoolBelongTo: 4,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "红星小学（原松岗第三小学）",
    schoolClass: 5,
    belongsText:
      "东至107国道，南至河滨南路，北至沙江路的松岗街道范围。主要社区有：松岗社区（部分），花果山社区，松涛社区（部分），红星社区格布村、温屋村、蚝涌村、松新村、西坊村、湾头村、南岸村，松岗社区坑尾村，洪桥头社区。主要小区有：红星花园、松河瑞园。\n(2)北至沙江路，西至107国道，南至东方大道的松岗街道范围。主要社区有：楼岗社区，东方社区（部分），松岗社区麒麟新村、东风村，山门社区。主要小区有：宝利豪庭、联投东方华府（1、2期）、居乐苑、集信大厦、翡翠阳光名苑、汇智百盛花园、璟荟名庭。",
    schoolType: 1,
    schoolTel: "23019363",
    educationType: 1,
    schoolBelongTo: 4,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "天骄小学（集团）东方小学",
    schoolClass: 8,
    belongsText:
      "北至松明大道，东至107国道；西至松瑞路、北至东方大道的松岗街道行政区域范围；主要社区有：东方社区、潭头社区、红星社区西坊村、湾头村、南岸村、格布新村、龙门村，松涛社区（部分）。主要小区有：桂景园、松涛花园、联投东方（三期）。",
    schoolType: 1,
    schoolTel: "29693111",
    educationType: 1,
    schoolBelongTo: 4,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "天骄小学（集团）潭头小学",
    schoolClass: 6,
    belongsText:
      "北至松明大道，东至107国道；西至松瑞路、北至东方大道的松岗街道行政区域范围；主要社区有：东方社区、潭头社区、红星社区西坊村、湾头村、南岸村、格布新村、龙门村，松涛社区（部分）。主要小区有：桂景园、松涛花园、联投东方（三期）。",
    schoolType: 1,
    schoolTel: "27060658",
    educationType: 1,
    schoolBelongTo: 4,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "文山小学",
    schoolClass: 4,
    belongsText:
      "北至松明大道，东至107国道；西至松瑞路、北至东方大道的松岗街道行政区域范围；主要社区有：东方社区、潭头社区、红星社区西坊村、湾头村、南岸村、格布新村、龙门村，松涛社区（部分）。主要小区有：桂景园、松涛花园、联投东方（三期）。",
    schoolType: 1,
    schoolTel: "27203661",
    educationType: 1,
    schoolBelongTo: 4,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "松岗实验学校（小学部）",
    schoolClass: 6,
    belongsText:
      "主要社区有：溪头、沙浦、沙浦围、朗下、碧头、江边、松岗社区坑尾村。主要小区有：宏发君域、中海西岸华府、富通御岭公馆、宝安山庄、松河瑞园、满京华小区、新世界松风明月花园、深铁璟城;\n(2)洪桥头社区仅可报沙溪小学和艺展小学。",
    schoolType: 1,
    schoolTel: "27207987",
    educationType: 1,
    schoolBelongTo: 4,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "沙溪小学",
    schoolClass: 8,
    belongsText:
      "主要社区有：溪头、沙浦、沙浦围、朗下、碧头、江边、松岗社区坑尾村。主要小区有：宏发君域、中海西岸华府、富通御岭公馆、宝安山庄、松河瑞园、满京华小区、新世界松风明月花园、深铁璟城;\n(2)洪桥头社区仅可报沙溪小学和艺展小学。",
    schoolType: 1,
    schoolTel: "27713173",
    educationType: 1,
    schoolBelongTo: 4,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "艺展小学",
    schoolClass: 5,
    belongsText:
      "主要社区有：溪头、沙浦、沙浦围、朗下、碧头、江边、松岗社区坑尾村。主要小区有：宏发君域、中海西岸华府、富通御岭公馆、宝安山庄、松河瑞园、满京华小区、新世界松风明月花园、深铁璟城;\n(2)洪桥头社区仅可报沙溪小学和艺展小学。",
    schoolType: 1,
    schoolTel: "27808801",
    educationType: 1,
    schoolBelongTo: 4,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "海韵学校（集团）红星实验学校(小学部）",
    schoolClass: 4,
    belongsText:
      "主要社区有：溪头、沙浦、沙浦围、朗下、碧头、江边、松岗社区坑尾村。主要小区有：宏发君域、中海西岸华府、富通御岭公馆、宝安山庄、松河瑞园、满京华小区、新世界松风明月花园、深铁璟城;\n(2)洪桥头社区仅可报沙溪小学和艺展小学。",
    schoolType: 1,
    schoolTel: "13316813407",
    educationType: 1,
    schoolBelongTo: 4,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安中学（集团）第二实验学校（小学部）",
    schoolClass: 4,
    belongsText:
      "主要社区有：溪头、沙浦、沙浦围、朗下、碧头、江边、松岗社区坑尾村。主要小区有：宏发君域、中海西岸华府、富通御岭公馆、宝安山庄、松河瑞园、满京华小区、新世界松风明月花园、深铁璟城;\n(2)洪桥头社区仅可报沙溪小学和艺展小学。",
    schoolType: 1,
    schoolTel: "27784946",
    educationType: 1,
    schoolBelongTo: 4,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "燕山学校（小学部）",
    schoolClass: 6,
    belongsText: "燕罗街道所有行政区域",
    schoolType: 1,
    schoolTel: "27070058",
    educationType: 1,
    schoolBelongTo: 4,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安区实验学校（集团）燕川实验学校（小学部）",
    schoolClass: 4,
    belongsText: "燕罗街道所有行政区域",
    schoolType: 1,
    schoolTel: "29929908",
    educationType: 1,
    schoolBelongTo: 4,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "天骄小学（集团）罗田小学",
    schoolClass: 4,
    belongsText: "燕罗街道所有行政区域",
    schoolType: 1,
    schoolTel: "23094593",
    educationType: 1,
    schoolBelongTo: 4,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "松岗中学（初中部）",
    schoolClass: 14,
    belongsText:
      "（1）松岗街道：所有行政区域；\n（2）燕罗街道：洪桥头社区、山门社区",
    schoolType: 1,
    schoolTel: "29896010",
    educationType: 2,
    schoolBelongTo: 4,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "可分享燕山学校、燕川实验学校初中部共享学区学位",
  },
  {
    schoolName: "松岗实验学校（初中部）",
    schoolClass: 6,
    belongsText:
      "（1）松岗街道：所有行政区域；\n（2）燕罗街道：洪桥头社区、山门社区",
    schoolType: 1,
    schoolTel: "27207987",
    educationType: 2,
    schoolBelongTo: 4,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "海韵学校（集团）红星实验学校（初中部）",
    schoolClass: 4,
    belongsText:
      "（1）松岗街道：所有行政区域；\n（2）燕罗街道：洪桥头社区、山门社区",
    schoolType: 1,
    schoolTel: "13316813407",
    educationType: 2,
    schoolBelongTo: 4,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安中学（集团）第二实验学校（初中部）",
    schoolClass: 4,
    belongsText:
      "（1）松岗街道：所有行政区域；\n（2）燕罗街道：洪桥头社区、山门社区",
    schoolType: 1,
    schoolTel: "27784946",
    educationType: 2,
    schoolBelongTo: 4,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "燕山学校（初中部）",
    schoolClass: 8,
    belongsText:
      "（1）燕罗街道所有行政区域；\n（2）南至松白路、北至沙江路、西至107国道松岗街道松岗社区（部分）。",
    schoolType: 1,
    schoolTel: "27071046",
    educationType: 2,
    schoolBelongTo: 4,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安区实验学校（集团）燕川实验学校（初中部）",
    schoolClass: 6,
    belongsText:
      "（1）燕罗街道所有行政区域；\n（2）南至松白路、北至沙江路、西至107国道松岗街道松岗社区（部分）。",
    schoolType: 1,
    schoolTel: "29929908",
    educationType: 2,
    schoolBelongTo: 4,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
];
