export default [
  {
    schoolName: "宝安中学外国语学校（集团）宝城小学（借址宝安中学外国语学校）",
    schoolClass: 4,
    belongsText:
      "107国道以东，创业二路以南，广深高速公路—边检路以西，湖滨路以北宝安所辖区域。",
    schoolType: 1,
    schoolTel: "27789090",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安中学外国语学校（小学部）",
    schoolClass: 6,
    belongsText:
      "107国道以东，创业二路以南，广深高速公路—边检路以西，湖滨路以北宝安所辖区域。",
    schoolType: 1,
    schoolTel: "27755399",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安中学外国语学校（集团）新安湖小学",
    schoolClass: 4,
    belongsText:
      "107国道以东，新圳路以北，前进路以西，创业二路以南区域（包括7、8、9、10区等）。",
    schoolType: 1,
    schoolTel: "27788931",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝民小学",
    schoolClass: 6,
    belongsText:
      "（1）前进路以东，新圳路以北，新安二路-新安三路-创业路-广深高速公路以西，裕安二路以南区域（19-22、26-28区）；（2）广深高速公路以东，上川路以南宝安所辖区域（包括67-72区等）；（3）新安二路、新安三路以东，洪浪南路以北，广深高速公路以西，创业二路以南区域（20、23区）；（4）海安苑、尖岗山壹号、新世界誉名别苑、新世纪名镌、万科未来之光。",
    schoolType: 1,
    schoolTel: "27788684",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "灵芝小学",
    schoolClass: 4,
    belongsText:
      "（1）前进路以东，新圳路以北，新安二路-新安三路-创业路-广深高速公路以西，裕安二路以南区域（19-22、26-28区）；（2）广深高速公路以东，上川路以南宝安所辖区域（包括67-72区等）；（3）新安二路、新安三路以东，洪浪南路以北，广深高速公路以西，创业二路以南区域（20、23区）；（4）海安苑、尖岗山壹号、新世界誉名别苑、新世纪名镌、万科未来之光。",
    schoolType: 1,
    schoolTel: "23500662",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安中学（集团）实验学校（小学部）",
    schoolClass: 8,
    belongsText:
      "（1）前进路以东，新圳路以北，新安二路-新安三路-创业路-广深高速公路以西，裕安二路以南区域（19-22、26-28区）；（2）广深高速公路以东，上川路以南宝安所辖区域（包括67-72区等）；（3）新安二路、新安三路以东，洪浪南路以北，广深高速公路以西，创业二路以南区域（20、23区）；（4）海安苑、尖岗山壹号、新世界誉名别苑、新世纪名镌、万科未来之光。",
    schoolType: 1,
    schoolTel: "27083919",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安中学外国语学校（集团）新蕾小学",
    schoolClass: 5,
    belongsText:
      "（1）前进路以东，新圳路以北，新安二路-新安三路-创业路-广深高速公路以西，裕安二路以南区域（19-22、26-28区）；（2）广深高速公路以东，上川路以南宝安所辖区域（包括67-72区等）；（3）新安二路、新安三路以东，洪浪南路以北，广深高速公路以西，创业二路以南区域（20、23区）；（4）海安苑、尖岗山壹号、新世界誉名别苑、新世纪名镌、万科未来之光。",
    schoolType: 1,
    schoolTel: "23092802",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "海韵学校(小学部)",
    schoolClass: 6,
    belongsText:
      "（1）玉律路以南，裕安路、宝兴路以北，宝安大道以西至海边；（2）海语西湾。",
    schoolType: 1,
    schoolTel: "23349864",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "滨海小学（集团）海裕小学",
    schoolClass: 6,
    belongsText: "裕安路以北，海城路以南，宝安大道以西，兴业路以东区域。",
    schoolType: 1,
    schoolTel: "23006087",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安小学",
    schoolClass: 8,
    belongsText:
      "（1）玉律路以北，新安六路以南，宝安大道以西，兴业路以东区域；（2）新安六路以北，西乡河以南，宝源路以西三角区域。",
    schoolType: 1,
    schoolTel: "29789225",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "孝德学校（小学部）",
    schoolClass: 6,
    belongsText: "创业二路以北，前进路以东，上川路以南，广深高速公路以西区域。",
    schoolType: 1,
    schoolTel: "29029114",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "上合小学",
    schoolClass: 8,
    belongsText:
      "（1）前进路以东，裕安二路以北，广深高速公路以西，新安四路以南区域（包括31、32、33、35、36等）；（2）73和74区中的区域。",
    schoolType: 1,
    schoolTel: "27968023",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安区实验学校(小学部)",
    schoolClass: 10,
    belongsText:
      "（1）湖滨路以北，甲岸路以南，107国道以西，宝安大道以东区域；（2）湖滨路以北，新安西路以南，宝安大道以西至海边。",
    schoolType: 1,
    schoolTel: "29637686",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安区实验学校（集团）海乐实验学校(小学部)",
    schoolClass: 6,
    belongsText:
      "（1）湖滨路以北，甲岸路以南，107国道以西，宝安大道以东区域；（2）湖滨路以北，新安西路以南，宝安大道以西至海边。",
    schoolType: 1,
    schoolTel: "27588718,29955688",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安区实验学校（集团）安乐小学",
    schoolClass: 6,
    belongsText:
      "（1）甲岸路以北，创业一路以南，107国道以西，宝安大道以东（41-44区）；（2）创业一路以北，裕安路以南，107国道以西，翻身路以东区域（45区）。",
    schoolType: 1,
    schoolTel: "27863352",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "可分享海乐实验学校学位",
  },
  {
    schoolName: "宝安小学（集团）翻身小学",
    schoolClass: 7,
    belongsText:
      "创业一路以北，新安五路以南，107国道以西，宝安大道以东区域（包括45、47、48、49、50区）。",
    schoolType: 1,
    schoolTel: "27362379",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "弘雅小学",
    schoolClass: 6,
    belongsText:
      "107国道以东，上川路以北，前进路以西，新安五路以南区域(34区)。",
    schoolType: 1,
    schoolTel: "27833749",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "建安小学",
    schoolClass: 7,
    belongsText:
      "107国道以东，创业二路以北，前进路以西，上川路以南区域（包括24、25、29、30区等）。",
    schoolType: 1,
    schoolTel: "27888308",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "裕安学校(小学部)",
    schoolClass: 4,
    belongsText:
      "107国道以东，创业二路以北，前进路以西，上川路以南区域（包括24、25、29、30区等）。",
    schoolType: 1,
    schoolTel: "29091168",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安区实验学校（集团）海旺学校(小学部)",
    schoolClass: 4,
    belongsText: "新安西路以北，创业路、宝华路以南，宝安大道以西至海边。",
    schoolType: 1,
    schoolTel: "29360159",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安中学（集团）海天学校（小学部）",
    schoolClass: 6,
    belongsText: "新安西路以北，创业路、宝华路以南，宝安大道以西至海边。",
    schoolType: 1,
    schoolTel: "27899691",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "滨海小学",
    schoolClass: 6,
    belongsText: "创业一路、宝华路以北，裕安路、宝兴路以南，翻身路以西至海边。",
    schoolType: 0,
    schoolTel: "29489721",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "可分享【海旺学校和宝安中学（集团）小学部】共享学区学位",
  },
  {
    schoolName: "文汇学校(小学部)",
    schoolClass: 6,
    belongsText: "107国道以东，创业二路以北，公园路以西，流塘路以南区域。",
    schoolType: 2,
    schoolTel: "27852832,27853160",
    educationType: 1,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安中学（集团）（初中部）",
    schoolClass: 16,
    belongsText:
      "107国道以东，新圳路以南，前进路以西,湖滨路以北宝安所辖区域（包括1-6区等）；前进路以东，裕安二路以南，广深高速公路-边检路以西，湖滨路以北宝安所辖区域（包括14-23、26-28区等）；广深高速公路以东，上川路以南宝安所辖区域（67-72区）。",
    schoolType: 1,
    schoolTel: "27590004",
    educationType: 2,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安中学外国语学校（初中部）",
    schoolClass: 10,
    belongsText:
      "107国道以东，新圳路以南，前进路以西,湖滨路以北宝安所辖区域（包括1-6区等）；前进路以东，裕安二路以南，广深高速公路-边检路以西，湖滨路以北宝安所辖区域（包括14-23、26-28区等）；广深高速公路以东，上川路以南宝安所辖区域（67-72区）。",
    schoolType: 1,
    schoolTel: "29963191",
    educationType: 2,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安中学（集团）实验学校（初中部）",
    schoolClass: 8,
    belongsText:
      "前进路以东，流塘路--公园路--西乡大道--广深高速--上川路以北（含山语华庭），平峦山公园以南，宝石路-铁岗水库以西。",
    schoolType: 1,
    schoolTel: "27084669",
    educationType: 2,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "新安中学（集团）外国语学校（初中部）",
    schoolClass: 8,
    belongsText:
      "前进路以东，流塘路--公园路--西乡大道--广深高速--上川路以北（含山语华庭），平峦山公园以南，宝石路-铁岗水库以西。",
    schoolType: 1,
    schoolTel: "23215701",
    educationType: 2,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "南方科技大学附属中学宝安学校（初中部）",
    schoolClass: 4,
    belongsText:
      "前进路以东，流塘路--公园路--西乡大道--广深高速--上川路以北（含山语华庭），平峦山公园以南，宝石路-铁岗水库以西。",
    schoolType: 1,
    schoolTel: "85909888,85909889",
    educationType: 2,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "新安中学（集团）第一实验学校(初中部)",
    schoolClass: 12,
    belongsText: "裕安路、宝兴路以北，海城路以南，宝安大道以西至海边。",
    schoolType: 1,
    schoolTel: "23061586,29789700",
    educationType: 2,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "海韵学校(初中部)",
    schoolClass: 8,
    belongsText: "裕安路、宝兴路以北，海城路以南，宝安大道以西至海边。",
    schoolType: 1,
    schoolTel: "23349864",
    educationType: 2,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安区实验学校(初中部)",
    schoolClass: 10,
    belongsText:
      "（1）湖滨路以北，甲岸路以南，107国道以西，宝安大道以东区域；（2）湖滨路以北，新安西路以南，宝安大道以西至海边。",
    schoolType: 1,
    schoolTel: "29637686",
    educationType: 2,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安区实验学校（集团）海乐实验学校(初中部)",
    schoolClass: 4,
    belongsText:
      "（1）湖滨路以北，甲岸路以南，107国道以西，宝安大道以东区域；（2）湖滨路以北，新安西路以南，宝安大道以西至海边。",
    schoolType: 1,
    schoolTel: "27588718",
    educationType: 2,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安中学（集团）海滨中学",
    schoolClass: 12,
    belongsText:
      "甲岸路以北,新安六路以南，107国道以西，宝安大道以东区域（包括41-50区等）。",
    schoolType: "分享学区 (可分享海乐实验学校学位)",
    schoolTel: "27839027",
    educationType: 2,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "新安中学（集团）（初中部）",
    schoolClass: 14,
    belongsText:
      "（1）107国道以东，新圳路以南，前进路以西,湖滨路以北宝安所辖区域（包括1-6区等）；（2） 107国道以东，前进路以西，新圳路以北，上川路以南区域(7-10、12、13、24、25、29、30区)。",
    schoolType: 2,
    schoolTel: "29993596",
    educationType: 2,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "文汇学校(初中部)",
    schoolClass: 16,
    belongsText:
      "（1）107国道以东，广深高速公路以西，裕安二路以北，新安四路、新安五路以南区域（包括29-36区等）；（2）前进路以东，宝安公园以西，新安四路以北，西乡大道以南区域（73-76区等）。",
    schoolType: 2,
    schoolTel: "27852832",
    educationType: 2,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安区实验学校（集团）海旺学校(初中部)",
    schoolClass: 6,
    belongsText: "新安西路以北，裕安路以南，宝安大道以西至海边。",
    schoolType: 1,
    schoolTel: "29360159",
    educationType: 2,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "宝安中学（集团）海天学校（初中部）",
    schoolClass: 4,
    belongsText: "新安西路以北，裕安路以南，宝安大道以西至海边。",
    schoolType: 1,
    schoolTel: "27899691",
    educationType: 2,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "孝德学校（初中部）",
    schoolClass: 6,
    belongsText:
      "新安四路—前进路—流塘路—宝安公园以南，新安二路——洪浪北路以北，107国道以东，广深高速公路以西区域。",
    schoolType: 1,
    schoolTel: "29029114",
    educationType: 2,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "裕安学校（初中部）",
    schoolClass: 4,
    belongsText:
      "新安四路—前进路—流塘路—宝安公园以南，新安二路——洪浪北路以北，107国道以东，广深高速公路以西区域。",
    schoolType: 1,
    schoolTel: "29091168",
    educationType: 2,
    schoolBelongTo: 0,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
];
