export default [
  {
    schoolName: "桥头学校（小学部）",
    schoolClass: 8,
    belongsText:
      "（1）桥头、塘尾、新田、稔田、和平、展城社区；（2）新和社区宝安大道（以西）——永福路（以东）——福洲大道（以南）——宝安大道（以西）的原桥头社区管辖区域；（3）凤塘大道（南）——凤城花园北围墙（西北）——万新二路（西南）——大洋路（西北)——塘新路（东北）——宝安大道（东）——凤塘大道（南）的围合区域",
    schoolType: 1,
    schoolTel: "29797637",
    educationType: 1,
    schoolBelongTo: 2,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "塘尾万里学校(小学部)",
    schoolClass: 6,
    belongsText:
      "（1）桥头、塘尾、新田、稔田、和平、展城社区；（2）新和社区宝安大道（以西）——永福路（以东）——福洲大道（以南）——宝安大道（以西）的原桥头社区管辖区域；（3）凤塘大道（南）——凤城花园北围墙（西北）——万新二路（西南）——大洋路（西北)——塘新路（东北）——宝安大道（东）——凤塘大道（南）的围合区域",
    schoolType: 1,
    schoolTel: "27376834",
    educationType: 1,
    schoolBelongTo: 2,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "滨海小学（集团）福桥小学",
    schoolClass: 4,
    belongsText:
      "（1）桥头、塘尾、新田、稔田、和平、展城社区；（2）新和社区宝安大道（以西）——永福路（以东）——福洲大道（以南）——宝安大道（以西）的原桥头社区管辖区域；（3）凤塘大道（南）——凤城花园北围墙（西北）——万新二路（西南）——大洋路（西北)——塘新路（东北）——宝安大道（东）——凤塘大道（南）的围合区域",
    schoolType: 1,
    schoolTel: "23018905",
    educationType: 1,
    schoolBelongTo: 2,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "立新湖学校（小学部）",
    schoolClass: 4,
    belongsText:
      "（1）桥头、塘尾、新田、稔田、和平、展城社区；（2）新和社区宝安大道（以西）——永福路（以东）——福洲大道（以南）——宝安大道（以西）的原桥头社区管辖区域；（3）凤塘大道（南）——凤城花园北围墙（西北）——万新二路（西南）——大洋路（西北)——塘新路（东北）——宝安大道（东）——凤塘大道（南）的围合区域",
    schoolType: 1,
    schoolTel: "27384243",
    educationType: 1,
    schoolBelongTo: 2,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "福新小学",
    schoolClass: 8,
    belongsText:
      "（1）新和、和平、展城社区；（2）塘尾社区永福路（以西）——荔园路/景芳路（以北）——永和路（以东）——凤塘大道（以南）的原和平社区管辖区域；（3）金域豪庭、福侨花园；（4）福永、怀德、白石厦、聚福社区，御景水岸花园",
    schoolType: 2,
    schoolTel: "81463769",
    educationType: 1,
    schoolBelongTo: 2,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "滨海小学（集团）下十围小学",
    schoolClass: 6,
    belongsText:
      "1.福永、怀德、聚福、福围社区；2.白石厦社区：（1）广深公路以西区域；（2）广深公路以东：福永卫生监督所——富欣邦科技园——泰源百万年工业园——昌荣电机有限公司——凤凰山以南区域；3.御景水岸花园。",
    schoolType: 1,
    schoolTel: "29104250",
    educationType: 1,
    schoolBelongTo: 2,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "新安中学（集团）第二外国语学校（小学部）",
    schoolClass: 4,
    belongsText:
      "1.福永、怀德、聚福、福围社区；2.白石厦社区：（1）广深公路以西区域；（2）广深公路以东：福永卫生监督所——富欣邦科技园——泰源百万年工业园——昌荣电机有限公司——凤凰山以南区域；3.御景水岸花园。",
    schoolType: 1,
    schoolTel: "23224653",
    educationType: 1,
    schoolBelongTo: 2,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "新安中学（集团）第二外国语学校怀德小学（借址新中二外）",
    schoolClass: 4,
    belongsText:
      "1.福永、怀德、聚福、福围社区；2.白石厦社区：（1）广深公路以西区域；（2）广深公路以东：福永卫生监督所——富欣邦科技园——泰源百万年工业园——昌荣电机有限公司——凤凰山以南区域；3.御景水岸花园。",
    schoolType: 1,
    schoolTel: "23224653",
    educationType: 1,
    schoolBelongTo: 2,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "福永小学",
    schoolClass: 7,
    belongsText:
      "1.福永、聚福社区，御景水岸花园；2.怀德社区：（1）立新南路以东区域；（2） 立新南路以西南——福德路以西北——新安中学（集团）第二外国语学校西南围墙以东北——万科金色领域北围墙以北——宝安大道；（3）立新南路以西南——下十围路以西北——永福苑东北围墙以东北——英管山——立新南路；3.白石厦社区：（1）广深公路以西区域；（2）广深公路以东：福永卫生监督所——富欣邦科技园——泰源百万年工业园——昌荣电机有限公司——凤凰山以南区域。",
    schoolType: 0,
    schoolTel: "27391640",
    educationType: 1,
    schoolBelongTo: 2,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "【可分享下十围小学、新安中学(集团)第二外国语学校小学部、新安中学（集团）第二外国语学校怀德小学学位】",
  },
  {
    schoolName: "凤凰学校(小学部)",
    schoolClass: 6,
    belongsText:
      "（1）凤凰、稔田、新田社区，福永花苑、时代景苑、同和凤凰花苑、保馨苑，碧桂园领寓、兴益科技大楼、兴益工业城、凤凰新天片区 ；（2）凤塘大道（南）——凤城花园北围墙（西北）——万新二路（西南）——大洋路（西北)——塘新路（东北）——宝安大道（东）——凤塘大道（南）的围合区域。",
    schoolType: 1,
    schoolTel: "81461764",
    educationType: 1,
    schoolBelongTo: 2,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "可分享兴围小学和航星学校小学部的学位",
  },
  {
    schoolName: "滨海小学（集团）文昌小学",
    schoolClass: 6,
    belongsText:
      "（1）凤凰、稔田、新田社区，福永花苑、时代景苑、同和凤凰花苑、保馨苑，碧桂园领寓、兴益科技大楼、兴益工业城、凤凰新天片区 ；（2）凤塘大道（南）——凤城花园北围墙（西北）——万新二路（西南）——大洋路（西北)——塘新路（东北）——宝安大道（东）——凤塘大道（南）的围合区域。",
    schoolType: 1,
    schoolTel: "23592510",
    educationType: 1,
    schoolBelongTo: 2,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "滨海小学（集团）兴围小学",
    schoolClass: 6,
    belongsText: "兴围、福围社区、机场（福永片区）。",
    schoolType: 1,
    schoolTel: "27502505",
    educationType: 1,
    schoolBelongTo: 2,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "航星学校（小学部）",
    schoolClass: 4,
    belongsText: "兴围、福围社区、机场（福永片区）。",
    schoolType: 1,
    schoolTel: "23303890",
    educationType: 1,
    schoolBelongTo: 2,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "桥头学校（初中部）",
    schoolClass: 6,
    belongsText:
      "（1）桥头、塘尾、和平、展城、新田、稔田社区；（2）新和社区宝安大道（以西）——永福路（以东）——福洲大道（以南）——宝安大道（以西）的原桥头社区管辖区域；（3）凤塘大道（南）——凤城花园北围墙（西北）——万新二路（西南）——大洋路（西北)——塘新路（东北）——宝安大道（东）——凤塘大道（南）的围合区域。",
    schoolType: 1,
    schoolTel: "29797637",
    educationType: 2,
    schoolBelongTo: 2,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "塘尾万里学校(初中部)",
    schoolClass: 8,
    belongsText:
      "（1）桥头、塘尾、和平、展城、新田、稔田社区；（2）新和社区宝安大道（以西）——永福路（以东）——福洲大道（以南）——宝安大道（以西）的原桥头社区管辖区域；（3）凤塘大道（南）——凤城花园北围墙（西北）——万新二路（西南）——大洋路（西北)——塘新路（东北）——宝安大道（东）——凤塘大道（南）的围合区域。",
    schoolType: 1,
    schoolTel: "27376834",
    educationType: 2,
    schoolBelongTo: 2,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "立新湖学校（初中部）",
    schoolClass: 2,
    belongsText:
      "（1）桥头、塘尾、和平、展城、新田、稔田社区；（2）新和社区宝安大道（以西）——永福路（以东）——福洲大道（以南）——宝安大道（以西）的原桥头社区管辖区域；（3）凤塘大道（南）——凤城花园北围墙（西北）——万新二路（西南）——大洋路（西北)——塘新路（东北）——宝安大道（东）——凤塘大道（南）的围合区域。",
    schoolType: 1,
    schoolTel: "27384243",
    educationType: 2,
    schoolBelongTo: 2,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "福永中学",
    schoolClass: 16,
    belongsText:
      "（1）福永、怀德、白石厦、聚福、福围、兴围、新和社区，御景水岸花园；（2）和平社区永和路（以西）——新裕二路（以南）——同富路（以西）——富桥工业区二区南围墙（以南）——永福路（以西）——福洲大道（以北）——松福大道（以东）——重庆路（以南）——永和路（以西）的原新和社区管辖区域；（3）展城社区松福大道（以西）——福洲大道（以北）——锦程路（以东）——蚝业路（以南）——松福大道（以西）以及蚝业路（以南）——展云路（以西）——福洲大道（以北）——海边区域的原新和社区管辖区域；（4）凤凰、新田、稔田、桥头、和平、展城社区；（5）塘尾社区永福路（以西）——荔园路/景芳路（以北）——永和路（以东）——凤塘大道（以南）的原和平社区管辖区域；（6）荔园小区。",
    schoolType: 1,
    schoolTel: "29605908",
    educationType: 2,
    schoolBelongTo: 2,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "新安中学（集团）第二外国语学校（初中部）",
    schoolClass: 8,
    belongsText:
      "（1）福永、怀德、白石厦、聚福、福围、兴围、新和社区，御景水岸花园；（2）和平社区永和路（以西）——新裕二路（以南）——同富路（以西）——富桥工业区二区南围墙（以南）——永福路（以西）——福洲大道（以北）——松福大道（以东）——重庆路（以南）——永和路（以西）的原新和社区管辖区域；（3）展城社区松福大道（以西）——福洲大道（以北）——锦程路（以东）——蚝业路（以南）——松福大道（以西）以及蚝业路（以南）——展云路（以西）——福洲大道（以北）——海边区域的原新和社区管辖区域；（4）凤凰、新田、稔田、桥头、和平、展城社区；（5）塘尾社区永福路（以西）——荔园路/景芳路（以北）——永和路（以东）——凤塘大道（以南）的原和平社区管辖区域；（6）荔园小区。",
    schoolType: 1,
    schoolTel: "23224653",
    educationType: 2,
    schoolBelongTo: 2,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "航星学校（初中部）",
    schoolClass: 4,
    belongsText:
      "（1）福永、怀德、白石厦、聚福、福围、兴围、新和社区，御景水岸花园；（2）和平社区永和路（以西）——新裕二路（以南）——同富路（以西）——富桥工业区二区南围墙（以南）——永福路（以西）——福洲大道（以北）——松福大道（以东）——重庆路（以南）——永和路（以西）的原新和社区管辖区域；（3）展城社区松福大道（以西）——福洲大道（以北）——锦程路（以东）——蚝业路（以南）——松福大道（以西）以及蚝业路（以南）——展云路（以西）——福洲大道（以北）——海边区域的原新和社区管辖区域；（4）凤凰、新田、稔田、桥头、和平、展城社区；（5）塘尾社区永福路（以西）——荔园路/景芳路（以北）——永和路（以东）——凤塘大道（以南）的原和平社区管辖区域；（6）荔园小区。",
    schoolType: 1,
    schoolTel: "23303890",
    educationType: 2,
    schoolBelongTo: 2,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
  {
    schoolName: "凤凰学校(初中部)",
    schoolClass: 6,
    belongsText:
      "（1）凤凰、新田、稔田社区，白石厦107国道以东片区；（2）凤塘大道（南）——凤城花园北围墙（西北）——万新二路（西南）——大洋路（西北)——塘新路（东北）——宝安大道（东）——凤塘大道（南）的围合区域；(3)福永、怀德、聚福、新和、兴围、福围、塘尾、桥头、和平、展城社区、白石厦107国道以西片区。",
    schoolType: 2,
    schoolTel: "81461764",
    educationType: 2,
    schoolBelongTo: 2,
    longitude: 0,
    latitude: 0,
    belongs: [],
    memo: "",
  },
];
